name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutCode
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls



    # 0. Checkout the code from the repository
    # 1. Install dependencies of our react application
    # 2. Execute automated tests