name: 09 - Using Functions

on:
  pull_request:
  workflow_dispatch:


jobs:
  echo1:
    runs-on: ubuntu-latest
    steps:
      - name: Print PR title
        run: echo "${{github.event.pull_request.title}}"
      - name: Print PR labels
        run: |
          cat << EOF
          ${{toJSON(github.event.pull_request.labels)}}     #print all labels from the pull request in json string format
          EOF
      - name: Bug step
        if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix')}} #if not cancelled and title of PR contains fix
        run: echo "I am a bug fix"
      - name: Sleep for 20 seconds
        run: sleep 20                # pause the run to be able to cancel the workflow after triggering it
      - name: Failing step
        run: exit 1                  #simple exit with non-zero code
      - name: I will be skipped
        if: ${{success()}}           #execute only if its successful (previous step)
        run: echo "I will print if previous steps succeed"
      - name: I will execute
        if: ${{failure()}}           #execute if previous step fails
        run: echo "I will print if any previous step fails"
      - name: I will execute
        if: ${{ !cancelled()}}
        run: echo "I will always print, except when the workflow is cancelled"
      - name: I will execute when cancelled
        if: ${{ cancelled()}}
        run: echo "I will  print if the workflow has been cancelled"