name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success
        
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:                                              # define outputs at job level
      build-status: ${{steps.build.outputs.status}}       # reference to steps. id . outputs . name-key, to input variable build-status
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      
      - name: Build
        id: build
        run: |
          echo "$GITHUB_OUTPUT"
          echo "status=${{inputs.build-status}}" >> "$GITHUB_OUTPUT"      # key/value appended to the file referenced by github output variable
          echo "output1=value1" >> "$GITHUB_OUTPUT"
          echo "output2=value2" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{needs.build.outputs.build-status == 'success'}}           # needs . job build . outputs . output build-status input variable
    steps:
      - name: Deploy
        run: echo "Deploying"
