name: 13 - Using Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: whether to execute cache step
        type: boolean
        default: true
      node-version:
        description: Node Version
        type: choice
        options:
          - 18.x
          - 20.x
          - 21.x
        default: 20.x
            
jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: 13-caching/react-app   # define working directory for run under job level. this will apply to all steps runs
    outputs:
      deps-cache-key: ${{steps.cache-key.outputs.CACHE_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
      - name: Calculate cache key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{hashFiles('13-caching/react-app/package-lock.json')}}" >> "$GITHUB_OUTPUT"
      - name: Dowload cached dependencies
        uses: actions/cache@v3
        if: ${{inputs.use-cache}}
        id: cache                    # use id cache becuase we will use it 
        with: 
          path:  13-caching/react-app/node_modules
          #key: deps-node-modules-dollar{{hashFiles('13-caching/react-app/package-lock.json')}} # define key with value 
          key: steps.cache-key.outputs.CACHE_KEY

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit !='true'
        run: npm ci

  lint-test:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run: 
        working-directory: 13-caching/react-app   # define working directory for run under job level. this will apply to all steps runs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
      - name: Dowload cached dependencies
        uses: actions/cache@v3
        if: ${{inputs.use-cache}}
        id: cache                    # use id cache becuase we will use it 
        with: 
          path:  13-caching/react-app/node_modules
          key: ${{needs.install-deps.outputs.deps-cache-key}}
      - name: Testing
        run: npm run test
      - name: Linting
        run: echo "Linting..."
     
  build:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run: 
        working-directory: 13-caching/react-app   # define working directory for run under job level. this will apply to all steps runs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}
      - name: Dowload cached dependencies
        uses: actions/cache@v3
        if: ${{inputs.use-cache}}
        id: cache                    # use id cache becuase we will use it 
        with: 
          path:  13-caching/react-app/node_modules
          key: ${{needs.install-deps.outputs.deps-cache-key}}
      #- name: Testing
      #  run: npm run test
      - name: Building
        run: npm run build
      #- name: Depoying to nonprod
      #  run: echo "Deploying to nonprod"

    # 1. Checkout the code
    # 2. install dependencies
    # 3. execute unit testing , building app
    # 4. Deploy to a nonprod environment

