name: 15 - Working with Matrices

on:
  workflow_dispatch:


jobs:
  backwards-compatibility:
    name: ${{matrix.os}}-${{matrix.node-version}}  # name of the particular combination version
    runs-on: ${{matrix.os}}                           # old ubuntu-latest
    strategy:                           # define strategy and matix values, syntax
      fail-fast: true             # false: when one job fails, other jobs will continue,  by default its true, so other jobs fail too
      matrix:
        node-version: ['18.x', '20.x', '21.x']
        os:
            - ubuntu-latest
            - windows-latest
        include:                   # allows to extend the configuration, in this case assign 16.x to ubuntu only and not windows
          - os: ubuntu-latest
            node-version: '16.x'   # allows specific limited values and not to all OS
          - os: ubuntu-latest
            node-version: '21.x'
            tag: experimental       # add a matrix.tag , use this tag further.
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with: 
          node-version: ${{matrix.node-version}}
      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1
      - name: Peform some tests
        run: |
          echo "Runngs tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
          
      - name: Upload test results
        run: echo "Uploading test results"
  
  include-example:
    name: ${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red,green]
        shape: [circle, square]
        size: [samll,large]
        include:                    # opacity 50 added earlier, This will be added to all combinations with value 50
          - color: red
            opacity: 75
          - shape: circle
            opacity: 100           # this is last in order, so this value will have priority
          - color: red
            shape: triangle
          - opacity: 50
        exclude:                    # exclude is processed before include option
          - opacity: 75
    steps:
      - name: Dummy Step
        run: echo "${{matrix.color}}-${{matrix.shape}}-${{matrix.size}}-${{matrix.opacity}}"
