name: 17 - 1 - Custom Actions - Composite
run-name: 17 - 1 - Custom Actions - Composite | env - ${{inputs.target-env}}

on:
  workflow_dispatch:
    inputs:
      target-env:
        description: Which enviroment to target for dependency installation
        type: choice
        options:
          - dev
          - prod

env:
  working-directory: 17-custom-actions/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and NPM dependencies
        uses: ./.github/actions/composite-cache-deps/        # Refer to Composite action and call
        with:
          node-version: 20.x
          working-dir: ${{env.working-directory}}
          target-env: ${{inputs.target-env}}
      - name: Test
        run: npm run test
      - name:
        run: npm run build

   