name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS | BB ${{inputs.base-branch}} - TB ${{inputs.target-branch}} - WD - ${{inputs.working-dir}}

on:
  workflow_dispatch:
    inputs:
      base-branch:
        type: string
        default: main
      target-branch:
        type: string
        default: update-Dependencies
      working-dir:
        type: string
        default: 17-custom-actions/react-app
      debug:
        type: boolean
        default: false
    
permissions:          # This gives write permission for the generated github token below
  contents: write
  pull-requests: write 
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for dependency updates
        id: update-deps
        uses: ./.github/actions/js-dependency-update      # Refer to JS action and call
        with:
          base-branch: ${{inputs.base-branch}}
          head-branch: ${{inputs.target-branch}}
          working-directory: ${{inputs.working-dir}}
          gh-token: ${{ secrets.GITHUB_TOKEN}}  # automatically created token using secrets key word. for within repository.
          debug: ${{inputs.debug}}
      - name: Pring custom action output
        run: |
          echo "Updates available: ${{steps.update-deps.outputs.updates-available}}"
   